language:
  - swift
osx_image: xcode10.1
xcode_workspace: Swift/AWSKinesisVideoWebRTCDemoApp.xcworkspace
script:
  - xcodebuild -workspace Swift/AWSKinesisVideoWebRTCDemoApp.xcworkspace -scheme AWSKinesisVideoWebRTCDemoApp -sdk iphoneos build
after_success:
  - bash <(curl -s https://codecov.io/bash)
